Feature: Create, Edit, Save and Run Queries

  Scenario Outline: Create and Edit a New Query
    Given I am logged into eTap
    And a query category has been created called 'Lucene Testing'
    When I click Queries on the main menu
    And I click on the 'Lucene Testing' category
    And I click 'New Query' on the Edit Query Category page
    And I set the Name to '<query_name>' on the Create a New Query page
    And I set the data return type to 'Accounts' on the Create a New Query page
    And I set the Available Fields category to '<field_category>' on the Create a New Query page
    And I click on '<field_name>' under Available Fields on the Create a New Query page
    And I set the inputs with '<ids>' with an optional '<prefix>' with '<values>' for type <type>
    And I click Save And 'Preview'
    And I click Edit on the query preview screen
    And I set the data return type to 'Accounts' on the Create a New Query page
    And I click Queries on the main menu
    And I click on the 'Lucene Testing' category
    And I click delete below the '<query_name>' query on the Create a New Query page
    And I click Yes to permanently delete the item
    Examples:
      | query_name                                         | field_category     | field_name                               | type              | prefix                                               | ids                                                      | values                                   |
      | Account-Account Created By 1                       | Account            | Account Created By                       | account           |                                                      | entityRoleCreatorSelectButton                            | /2                                       |
      | Account-Account Created By 2                       | Account            | Account Created By                       | account           |                                                      | userAsentityRoleCreator                                  |                                          |
      | Account-Account Last Modified By 1                 | Account            | Account Last Modified By                 | account           |                                                      | entityRoleModifierSelectButton                           | /2                                       |
      | Account-Account Last Modified By 2                 | Account            | Account Last Modified By                 | account           |                                                      | userAsentityRoleModifier                                 |                                          |
      | Account-Account Name 1                             | Account            | Account Name                             | AccountTextValues | TestEntityRoleForNamesData                           | values                                                   | John Carr                                |
      | Account-Account Name 2                             | Account            | Account Name                             | AccountTextValues | TestEntityRoleForNamesData                           | values                                                   | John Carr, Spencer Murphy                |
      | Account-Account Name 3                             | Account            | Account Name                             | AccountTextValues | TestEntityRoleForNamesData                           | values                                                   | John Carr, Spencer Murphy,Xandra Harrison |
      | Account-Account Number 1                           | Account            | Account Number                           | numRange          | TestEntityRoleForIdRangeData                         | comparisonKey, id, comparison2Key, id2                   | Greater Than, 3, Less Than, 5            |
      | Account-Account Number 2                           | Account            | Account Number                           | numRange          | TestEntityRoleForIdRangeData                         | comparisonKey, id                                        | Equal To, 7                              |
      | Account-Account Recognition Name 1                 | Account            | Account Recognition Name                 | textValues        | testByName(TestCustomerForRecognitionNamesData)      | values                                                   | John Carr                                |
      | Account-Account Recognition Name 2                 | Account            | Account Recognition Name                 | textValues        | testByName(TestCustomerForRecognitionNamesData)      | values                                                   | John Carr, Spencer Murphy                |
      | Account-Account Recognition Name 3                 | Account            | Account Recognition Name                 | textValues        | testByName(TestCustomerForRecognitionNamesData)      | values                                                   | none                                     |
      | Account-Account Recognition Name 4                 | Account            | Account Recognition Name                 | textValues        | testByName(TestCustomerForRecognitionNamesData)      | values                                                   | any                                      |
      | Account-Account Recognition Types 1                | Account            | Account Recognition Types                | checkboxes        | testByName(TestCustomerForRecognitionTypesData)      | recognitionTypes                                         | 0,2,3                                    |
      | Account-Account Recognition Types 2                | Account            | Account Recognition Types                | checkboxes        | testByName(TestCustomerForRecognitionTypesData)      | recognitionTypes                                         | 1                                        |
      | Account-Account Role 1                             | Account            | Account Role                             | checkboxes        |  |  |  |
      | Account-Account Role 2                             | Account            | Account Role                             | checkboxes        | testByName(TestEntityRoleForRoleTypesData)           | types                                                    | com.eTapestry.app.core.User              |
      | Account-Account Role 3                             | Account            | Account Role                             | checkboxes        | testByName(TestEntityRoleForRoleTypesData)           | types                                                    | com.eTapestry.app.core.Team, com.eTapestry.app.core.Tribute |
      | Account-Address Lines 1                            | Account            | Address Lines                            | textValues        | TestEntityRoleForAddressesData                       | values                                                   | 12884 Fox Road                           |
      | Account-Address Lines 2                            | Account            | Address Lines                            | textValues        | TestEntityRoleForAddressesData                       | values                                                   | 12884 Fox Road, 1234 N St                |
      | Account-Address Lines 3                            | Account            | Address Lines                            | textValues        | TestEntityRoleForAddressesData                       | values                                                   | any                                      |
      | Account-Address Lines 4                            | Account            | Address Lines                            | textValues        | TestEntityRoleForAddressesData                       | values                                                   | none                                     |
      | Account-City 1                                     | Account            | City                                     | textValues        | TestEntityRoleForCitiesData                          | cities                                                   | Noblesville                              |
      | Account-City 2                                     | Account            | City                                     | textValues        | TestEntityRoleForCitiesData                          | cities                                                   | Noblesville, Carmel                      |
      | Account-City 3                                     | Account            | City                                     | textValues        | TestEntityRoleForCitiesData                          | cities                                                   | any                                      |
      | Account-City 4                                     | Account            | City                                     | textValues        | TestEntityRoleForCitiesData                          | cities                                                   | none                                     |
      | Account-County 1                                   | Account            | County                                   | textValues        | testByName(TestEntityRoleForCountiesData)            | counties                                                 | Hamilton                                 |
      | Account-County 2                                   | Account            | County                                   | textValues        | testByName(TestEntityRoleForCountiesData)            | counties                                                 | Hamilton, Monroe                         |
      | Account-County 3                                   | Account            | County                                   | textValues        | testByName(TestEntityRoleForCountiesData)            | counties                                                 | any                                      |
      | Account-County 4                                   | Account            | County                                   | textValues        | testByName(TestEntityRoleForCountiesData)            | counties                                                 | none                                     |
      | Account-Email Address 1                            | Account            | Email Address                            | textValues        | testByName(TestEntityRoleForEmailsData)              | values                                                   | John.Carr@blackbaud.com                  |
      | Account-Email Address 2                            | Account            | Email Address                            | textValues        | testByName(TestEntityRoleForEmailsData)              | values                                                   | John.Carr@blackbaud.com, A.E@bb.com      |
      | Account-Email Address 3                            | Account            | Email Address                            | textValues        | testByName(TestEntityRoleForEmailsData)              | values                                                   | none                                     |
      | Account-Email Address 4                            | Account            | Email Address                            | textValues        | testByName(TestEntityRoleForEmailsData)              | values                                                   | any                                      |
      | Account-Envelope Salutation 1                      | Account            | Envelope Salutation                      | textValues        | testByName(TestEntityRoleForEnvelopeSalutationsData) | values                                                   | Mr. John Carr                            |
      | Account-Envelope Salutation 2                      | Account            | Envelope Salutation                      | textValues        | testByName(TestEntityRoleForEnvelopeSalutationsData) | values                                                   | Mr. John Carr, Mr. Spencer Murphy        |
      | Account-Envelope Salutation 3                      | Account            | Envelope Salutation                      | textValues        | testByName(TestEntityRoleForEnvelopeSalutationsData) | values                                                   | none                                     |
      | Account-Envelope Salutation 4                      | Account            | Envelope Salutation                      | textValues        | testByName(TestEntityRoleForEnvelopeSalutationsData) | values                                                   | any                                      |
      | Account-First Name 1                               | Account            | First Name                               | textValues        | testByName(TestEntityRoleForFirstNamesData)          | values                                                   | John                                     |
      | Account-First Name 2                               | Account            | First Name                               | textValues        | testByName(TestEntityRoleForFirstNamesData)          | values                                                   | John, Spencer                            |
      | Account-First Name 3                               | Account            | First Name                               | textValues        | testByName(TestEntityRoleForFirstNamesData)          | values                                                   | none                                     |
      | Account-First Name 4                               | Account            | First Name                               | textValues        | testByName(TestEntityRoleForFirstNamesData)          | values                                                   | any                                      |
      | Account-Household Relationship 1                   | Account            | Household Relationship                   | select            | testByName(TestEntityRoleForHouseholdData)           | household                                                | 2                                        |
      | Account-Household Relationship 2                   | Account            | Household Relationship                   | select            | testByName(TestEntityRoleForHouseholdData)           | household                                                | 0                                        |
      | Account-Household Relationship 3                   | Account            | Household Relationship                   | select            | testByName(TestEntityRoleForHouseholdData)           | household                                                | 3                                        |
      | Account-Last Name 1                                | Account            | Last Name                                | AccountTextValues | TestEntityRoleForLastNamesData                       | values                                                   | Carr                                     |
      | Account-Last Name 2                                | Account            | Last Name                                | AccountTextValues | TestEntityRoleForLastNamesData                       | values                                                   | Carr, Murphy                             |
      | Account-Last Name 3                                | Account            | Last Name                                | AccountTextValues | TestEntityRoleForLastNamesData                       | values                                                   | Carr, Murphy, Harrison                   |
      | Account-Login Id Present 1                         | Account            | Login Id Present                         | radio             | testByName(TestEntityRoleForLoginIdData)             | withLoginId                                              | false                                    |
      | Account-Login Id Present 2                         | Account            | Login Id Present                         | radio             | testByName(TestEntityRoleForLoginIdData)             | withLoginId                                              | true                                     |
      | Account-Long Salutation 1                          | Account            | Long Salutation                          | textValues        | testByName(TestEntityRoleForLongSalutationsData)     | values                                                   | Mr. Carr, Mr. Murphy                     |
      | Account-Long Salutation 2                          | Account            | Long Salutation                          | textValues        | testByName(TestEntityRoleForLongSalutationsData)     | values                                                   | Mr. Carr                                 |
      | Account-Long Salutation 3                          | Account            | Long Salutation                          | textValues        | testByName(TestEntityRoleForLongSalutationsData)     | values                                                   | any                                      |
      | Account-Long Salutation 4                          | Account            | Long Salutation                          | textValues        | testByName(TestEntityRoleForLongSalutationsData)     | values                                                   | none                                     |
      | Account-Loyalty Ratings 1                          | Account            | Loyalty Ratings                          | checkboxes        | testByName(TestEntityRoleForLoyaltyRatingsData)      | loyaltyRatings                                           | 1, 2, 3, 4                               |
      | Account-Loyalty Ratings 2                          | Account            | Loyalty Ratings                          | checkboxes        | testByName(TestEntityRoleForLoyaltyRatingsData)      | loyaltyRatings                                           | 1, 3, 4                                  |
      | Account-Loyalty Ratings 3                          | Account            | Loyalty Ratings                          | checkboxes        | testByName(TestEntityRoleForLoyaltyRatingsData)      | loyaltyRatings                                           | 2                                        |
      | Account-Middle Name 1                              | Account            | Middle Name                              | textValues        | testByName(TestEntityRoleForMiddleNameData)          | values                                                   | Ann, Daniel                              |
      | Account-Middle Name 2                              | Account            | Middle Name                              | textValues        | testByName(TestEntityRoleForMiddleNameData)          | values                                                   | Ann                                      |
      | Account-Middle Name 3                              | Account            | Middle Name                              | textValues        | testByName(TestEntityRoleForMiddleNameData)          | values                                                   | none                                     |
      | Account-Middle Name 4                              | Account            | Middle Name                              | textValues        | testByName(TestEntityRoleForMiddleNameData)          | values                                                   | any                                      |
      | Account-Name Formats 1                             | Account            | Name Formats                             | checkboxes        | testByName(TestEntityRoleForNameFormatsData)         | formats                                                  | 0, 1, 2, 3                               |
      | Account-Name Formats 2                             | Account            | Name Formats                             | checkboxes        | testByName(TestEntityRoleForNameFormatsData)         | formats                                                  | 0, 2, 3                                  |
      | Account-Name Formats 3                             | Account            | Name Formats                             | checkboxes        | testByName(TestEntityRoleForNameFormatsData)         | formats                                                  | 1                                        |
      | Account-Old Formatted Address 1                    | Account            | Old Formatted Address                    | radio             | testByName(TestEntityRoleForOldFormatData)           | oldFormat                                                | false                                    |
      | Account-Old Formatted Address 2                    | Account            | Old Formatted Address                    | radio             | testByName(TestEntityRoleForOldFormatData)           | oldFormat                                                | true                                     |
      | Account-Opted Out 1                                | Account            | Opted Out                                | radio             | testByName(TestEntityRoleForOptOutData)              | optedOut                                                 | false                                    |
      | Account-Opted Out 2                                | Account            | Opted Out                                | radio             | testByName(TestEntityRoleForOptOutData)              | optedOut                                                 | true                                     |
      | Account-Persona Created By 1                       | Account            | Persona Created By                       | account           |                                                      | personaCreatorSelectButton                               | /2                                       |
      | Account-Persona Created By 2                       | Account            | Persona Created By                       | account           |                                                      | userAspersonaCreator                                     |                                          |
      | Account-Persona Last Modified By 1                 | Account            | Persona Last Modified By                 | account           |                                                      | personaModifierSelectButton                              | /2                                       |
      | Account-Persona Last Modified By 2                 | Account            | Persona Last Modified By                 | account           |                                                      | userAspersonaModifier                                    |                                          |
      | Account-Persona Note 1                             | Account            | Persona Note                             | textValues        | testByName(TestEntityRoleForNotesData)               | values                                                   | Major Donor                              |
      | Account-Persona Note 2                             | Account            | Persona Note                             | textValues        | testByName(TestEntityRoleForNotesData)               | values                                                   | Major Donor, Inactive                    |
      | Account-Persona Note 3                             | Account            | Persona Note                             | textValues        | testByName(TestEntityRoleForNotesData)               | values                                                   | none                                     |
      | Account-Persona Note 4                             | Account            | Persona Note                             | textValues        | testByName(TestEntityRoleForNotesData)               | values                                                   | any                                      |
      | Account-Phone Number 1                             | Account            | Phone Number                             | phone number      | TestEntityRoleForPhonesData                          | phoneNum                                                 | Voice, 1234567890                        |
      | Account-Phone Number 2                             | Account            | Phone Number                             | phone number      | TestEntityRoleForPhonesData                          | phoneNum                                                 | Voice, 1234567890, 1112223333            |
      | Account-Phone Number 3                             | Account            | Phone Number                             | phone number      | TestEntityRoleForPhonesData                          | phoneNum                                                 | Voice, none                              |
      | Account-Phone Number 4                             | Account            | Phone Number                             | phone number      | TestEntityRoleForPhonesData                          | phoneNum                                                 | Voice, any                               |
      | Account-Phone Number 5                             | Account            | Phone Number                             | phone number      | TestEntityRoleForPhonesData                          | phoneNum                                                 | Mobile, 1234567890                       |
      | Account-Postal Code 1                              | Account            | Postal Code                              | textValues        | testByName(TestEntityRoleForPostalCodeData)          | postalCodes                                              | 46060, 48721                             |
      | Account-Postal Code 2                              | Account            | Postal Code                              | textValues        | testByName(TestEntityRoleForPostalCodeData)          | postalCodes                                              | 46060                                    |
      | Account-Postal Code 3                              | Account            | Postal Code                              | textValues        | testByName(TestEntityRoleForPostalCodeData)          | postalCodes                                              | none                                     |
      | Account-Postal Code 4                              | Account            | Postal Code                              | textValues        | testByName(TestEntityRoleForPostalCodeData)          | postalCodes                                              | any                                      |
      | Account-Postal Code Length 1                       | Account            | Postal Code Length                       | numRange          | TestEntityRoleForPostalCodeLengthData                | comparisonKey, length, comparison2Key, length2           | Greater Than Or Equal To, 2              |
      | Account-Postal Code Length 2                       | Account            | Postal Code Length                       | numRange          | TestEntityRoleForPostalCodeLengthData                | comparisonKey, length                                    | Less Than Or Equal To, 6                 |
      | Account-Postal Code Radius 1                       | Account            | Postal Code Radius                       | radius            | TestEntityRoleForPostalCodeRadiusData                | postalCode, radius                                       | 46060, 15                                |
      | Account-Postal Code Radius 2                       | Account            | Postal Code Radius                       | radius            | TestEntityRoleForPostalCodeRadiusData                | postalCode, radius                                       | 48721, 25                                |
      | Account-Postal Code Range 1                        | Account            | Postal Code Range                        | textNumRange      | TestEntityRoleForPostalCodeRangeData                 | startPostalCode, endPostalCode                           | 46060, 48721                             |
      | Account-Privacy Status 1                           | Account            | Privacy Status                           | checkboxes        | testByName(TestEntityRoleForPrivacyStatusData)       | status                                                   | -1, 0, 1                                 |
      | Account-Privacy Status 2                           | Account            | Privacy Status                           | checkboxes        | testByName(TestEntityRoleForPrivacyStatusData)       | status                                                   | 0, 1                                     |
      | Account-Privacy Status 3                           | Account            | Privacy Status                           | checkboxes        | testByName(TestEntityRoleForPrivacyStatusData)       | status                                                   | 1                                        |
      | Account-Relationship Attributes 1                  | Account            | Relationship Attributes                  | relationship attributes | TestEntityRoleForRelationshipsData             | relationshipType, startDateStartString, startDateEndString, endDateStartString, endDateEndString | Parent / Child, 01/01/2000, 01/01/2010, 01/01/2000, 01/01/2010 |
      | Account-Relationship Attributes 2                  | Account            | Relationship Attributes                  | relationship attributes | TestEntityRoleForRelationshipsData             | relationshipType, startDateStartString, startDateEndString, endDateStartString, endDateEndString, relationshipRoleFrom, relationshipMatchingGift | Parent / Child, 01/01/2000, 01/01/2010, 01/01/2000, 01/01/2010 |
      | Account-Relationship Attributes 3                  | Account            | Relationship Attributes                  | relationship attributes | TestEntityRoleForRelationshipsData             | relationshipType, startDateStartString, startDateEndString, endDateStartString, endDateEndString, relationshipRoleFrom, relationshipMatchingGift | Parent / Child, 01/01/2000, , , 01/01/2010 |
      | Account-Relationship Attributes 4                  | Account            | Relationship Attributes                  | relationship attributes | TestEntityRoleForRelationshipsData             | relationshipType, startDateStartString, startDateEndString, endDateStartString, endDateEndString, relationshipRoleFrom, relationshipMatchingGift | Parent / Child, 01/01/2000, , 01/01/2000, |
      | Account-Relationship Attributes 5                  | Account            | Relationship Attributes                  | relationship attributes | TestEntityRoleForRelationshipsData             | relationshipType, startDateStartString, startDateEndString, endDateStartString, endDateEndString, relationshipMatchingGift | Parent / Child, 01/01/2000, 01/01/2010, 01/01/2000, 01/01/2010 |
      | Account-Relationship Attributes 6                  | Account            | Relationship Attributes                  | relationship attributes | TestEntityRoleForRelationshipsData             | relationshipType, dynamicStartDate.label, dynamicStartDateRange, dynamicEndDate.label, dynamicEndDateRange | Parent / Child, Dynamic, 26, Dynamic, 16 |
      | Account-Relationship Attributes 7                  | Account            | Relationship Attributes                  | relationship attributes | TestEntityRoleForRelationshipsData             | relationshipType, dynamicStartDate.label, dynamicStartDateRange, dynamicEndDate.label, dynamicEndDateRange | Parent / Child, Dynamic, 26, Dynamic, |
      | Account-Relationship Present 1                     | Account            | Relationship Present                     | radio             | testByName(TestEntityRoleForRelationshipData)        | hasRelationship                                          | false                                    |
      | Account-Relationship Present 2                     | Account            | Relationship Present                     | radio             | testByName(TestEntityRoleForRelationshipData)        | hasRelationship                                          | true                                     |
      | Account-Short Salutation 1                         | Account            | Short Salutation                         | textValues        | testByName(TestEntityRoleForShortSalutationsData)    | values                                                   | John, Spencer                            |
      | Account-Short Salutation 2                         | Account            | Short Salutation                         | textValues        | testByName(TestEntityRoleForShortSalutationsData)    | values                                                   | John                                     |
      | Account-Short Salutation 3                         | Account            | Short Salutation                         | textValues        | testByName(TestEntityRoleForShortSalutationsData)    | values                                                   | any                                      |
      | Account-Short Salutation 4                         | Account            | Short Salutation                         | textValues        | testByName(TestEntityRoleForShortSalutationsData)    | values                                                   | none                                     |
      | Account-State/Province 1                           | Account            | State/Province                           | textValues        | testByName(TestEntityRoleForStatesData)              | states                                                   | Indiana, Michigan                        |
      | Account-State/Province 2                           | Account            | State/Province                           | textValues        | testByName(TestEntityRoleForStatesData)              | states                                                   | Indiana                                  |
      | Account-State/Province 3                           | Account            | State/Province                           | textValues        | testByName(TestEntityRoleForStatesData)              | states                                                   | none                                     |
      | Account-State/Province 4                           | Account            | State/Province                           | textValues        | testByName(TestEntityRoleForStatesData)              | states                                                   | any                                      |
      | Account-Suffix 1                                   | Account            | Suffix                                   | textValues        | testByName(TestEntityRoleForSuffixesData)            | values                                                   | MD, M.D.                                 |
      | Account-Suffix 2                                   | Account            | Suffix                                   | textValues        | testByName(TestEntityRoleForSuffixesData)            | values                                                   | MD                                       |
      | Account-Suffix 3                                   | Account            | Suffix                                   | textValues        | testByName(TestEntityRoleForSuffixesData)            | values                                                   | none                                     |
      | Account-Suffix 4                                   | Account            | Suffix                                   | textValues        | testByName(TestEntityRoleForSuffixesData)            | values                                                   | any                                      |
      | Account-Target American URL Present 1              | Account            | Target American URL Present              | radio             | testByName(TestEntityRoleForTargetAmericanURLData)   | withURL                                                  | false                                    |
      | Account-Target American URL Present 2              | Account            | Target American URL Present              | radio             | testByName(TestEntityRoleForTargetAmericanURLData)   | withURL                                                  | true                                     |
      | Account-Title 1                                    | Account            | Title                                    | textValues        | testByName(TestEntityRoleForTitlesData)              | values                                                   | Mr., Mrs.                                |
      | Account-Title 2                                    | Account            | Title                                    | textValues        | testByName(TestEntityRoleForTitlesData)              | values                                                   | Mr.,                                     |
      | Account-Title 3                                    | Account            | Title                                    | textValues        | testByName(TestEntityRoleForTitlesData)              | values                                                   | none                                     |
      | Account-Title 4                                    | Account            | Title                                    | textValues        | testByName(TestEntityRoleForTitlesData)              | values                                                   | any                                      |
      | Account-Web Page 1                                 | Account            | Web Page                                 | textValues        | testByName(TestEntityRoleForWebPagesData)            | values                                                   | www.bb.com, www.nonprofit.com            |
      | Account-Web Page 2                                 | Account            | Web Page                                 | textValues        | testByName(TestEntityRoleForWebPagesData)            | values                                                   | www.bb.com                               |
      | Account-Web Page 3                                 | Account            | Web Page                                 | textValues        | testByName(TestEntityRoleForWebPagesData)            | values                                                   | any                                      |
      | Account-Web Page 4                                 | Account            | Web Page                                 | textValues        | testByName(TestEntityRoleForWebPagesData)            | values                                                   | none                                     |

      | Amounts-Household Largest Transaction 1             | Amounts           | Household Largest Transaction             | select          | testByName(TestTransactionForHHLargestData)           | key                                                        | (None Selected)                        |
      | Amounts-Household Largest Transaction 2             | Amounts           | Household Largest Transaction             | select          | testByName(TestTransactionForHHLargestData)           | key                                                        | 2                                      |
      | Amounts-Household Largest Transaction 3             | Amounts           | Household Largest Transaction             | select          | testByName(TestTransactionForHHLargestData)           | key                                                        | 7                                      |
      | Amounts-Individual Recurring Gift Schedule Amount 1 | Amounts           | Individual Recurring Gift Schedule Amount | numRange        | TestTransactionForRecurringGiftScheduleAmountData     | comparisonKey, amountString                                | Less Than Or Equal To, 20              |
      | Amounts-Individual Recurring Gift Schedule Amount 2 | Amounts           | Individual Recurring Gift Schedule Amount | numRange        | TestTransactionForRecurringGiftScheduleAmountData     | comparisonKey, amountString, comparison2Key, amount2String | Greater Than, 5, Less Than, 10         |
      | Amounts-Individual Transaction Balance 1            | Amounts           | Individual Transaction Balance            | numRange        | TestTransactionForBalanceData                         | comparisonKey, amountString                                | Equal To, 20                           |
      | Amounts-Individual Transaction Balance 2            | Amounts           | Individual Transaction Balance            | numRange        | TestTransactionForBalanceData                         | comparisonKey, amountString, comparison2Key, amount2String | Less Than, 100, Greater Than, 20       |
      | Amounts-Individual Transaction Deductible 1         | Amounts           | Individual Transaction Deductible         | numRange        | TestTransactionForDeductibleData                      | comparisonKey, amountString, comparison2Key, amount2String | Less Than, 100, Greater Than, 20       |
      | Amounts-Individual Transaction Deductible 2         | Amounts           | Individual Transaction Deductible         | numRange        | TestTransactionForDeductibleData                      | comparisonKey, amountString                                | Less Than Or Equal To, 100             |
      | Amounts-Individual Transaction Gifted 1             | Amounts           | Individual Transaction Gifted             | numRange        | TestTransactionForGiftedData                          | comparisonKey, amountString, comparison2Key, amount2String | Less Than, 100, Greater Than, 20       |
      | Amounts-Individual Transaction Gifted 2             | Amounts           | Individual Transaction Gifted             | numRange        | TestTransactionForGiftedData                          | comparisonKey, amountString                                | Greater Than Or Equal To, 100          |

      | Amounts - Individual Transaction Pledge Arrears    | Amounts            | Individual Transaction Pledge Arrears    | arrears           | testByName(TestTransactionForArrearsData)            | comparisonKey, amountString, dynamicDate, asOfDateString | Greater Than, 20, Custom Date, 7/15/2015 |
      | Amounts - Upgraded/Split Transaction Total Arrears | Amounts            | Upgraded/Split Transaction Total Arrears | arrears           | testByName(TestTransactionForSegmentedArrearsData)   | comparisonKey, amountString, dynamicDate, asOfDateString | Less Than, 100, Start of Next Month      |
      | Dates - Account Created Date 1                     | Dates              | Account Created Date                     | dateRange         | TestEntityRoleForCreatedDateData                     | dynamicDateRange, startDateString, endDateString         | Custom Range, 7/15/2015, 7/20/2015       |
      | Dates - Account Created Date 2                     | Dates              | Account Created Date                     | dateRange         | TestEntityRoleForCreatedDateData                     | dynamicDateRange                                         | Last 7 Days                              |
      | Dates-First/Last Journal Entry 1                   | Dates              | First/Last Journal Entry                 | firstLast         | TestJournalEntryForOrdinalData                       | key, count                                               | First, 10                                |
      | Dates-First/Last Journal Entry 2                   | Dates              | First/Last Journal Entry                 | firstLast         | TestJournalEntryForOrdinalData                       | key, count                                               | Third                                    |
      | Dates-First/Last Journal Entry 3                   | Dates              | First/Last Journal Entry                 | firstLast         | TestJournalEntryForOrdinalData                       | key, count                                               | Last, 5                                  |
      | Journal-Transaction Receipt Range 1                | Journal            | Transaction Receipt Range                | textNumRange      | TestTransactionForReceiptRangeData                   | startReceipt, endReceipt                                 | 2, 12                                    |
      | Journal-Transaction Receipt Range 2                | Journal            | Transaction Receipt Range                | textNumRange      | TestTransactionForReceiptRangeData                   | startReceipt, endReceipt                                 | any                                      |
      | Journal-Transaction Receipt Range 3                | Journal            | Transaction Receipt Range                | textNumRange      | TestTransactionForReceiptRangeData                   | startReceipt, endReceipt                                 | none                                     |
      | Defined Fields - Approaches 1                      | Commonly Used Fields     | Approaches                         | checkbox refs     | TestTransactionForApproachesData                     | approachRefs                                             | Direct Mail                              |
      | Defined Fields - Approaches 2                      | Commonly Used Fields     | Approaches                         | checkbox refs     | TestTransactionForApproachesData                     | approachRefs                                             | any                                      |
      | Defined Fields - Approaches 3                      | Commonly Used Fields     | Approaches                         | checkbox refs     | TestTransactionForApproachesData                     | approachRefs                                             | no                                       |
      | Defined Fields - Approaches 4                      | Commonly Used Fields     | Approaches                         | checkbox refs     | TestTransactionForApproachesData                     | approachRefs                                             | Direct Mail, Unsolicited                 |

  Scenario: Deleting Categories
    Given I am logged into eTap
    And I click Queries on the main menu
    And I click delete below the 'Lucene Testing' query category
    And I click Yes to permanently delete the item
    Then I should see the 'Lucene Testing' category has been removed from the page






